stages:
  - test
  - check

test_basic:
  stage: test
  script:
    - echo "Hello from GitLab CI/CD!"
    - echo "Testing basic functionality..."
    - echo "GitLab CI/CD is working!"

check_variables:
  stage: check
  script:
    - echo "Checking GitHub variables..."
    - echo "USERNAME $GITHUB_USERNAME..."
    - echo "GITHUB_SSH_KEY length $(expr length "${GITHUB_SSH_KEY:-}")"
  only:
    - main
  when: manual
