stages:
  - test
  - sync

test_basic:
  stage: test
  script:
    - echo "Hello from GitLab CI/CD!"
    - echo "Testing basic functionality..."
    - echo "GitLab CI/CD is working!"

sync_to_github:
  stage: sync
  image: alpine:latest
  before_script:
    - apk add --no-cache git openssh-client
    - eval $(ssh-agent -s)
    - echo "$GITLAB_SSH_KEY" | base64 -d | ssh-add -
    - echo "$GITHUB_SSH_KEY" | base64 -d | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan -H gitlab.com >> ~/.ssh/known_hosts
    - ssh-keyscan -H github.com >> ~/.ssh/known_hosts
    - git config --global user.email "ci@example.com"
    - git config --global user.name "GitLab CI"
  script:
    - echo "Starting GitHub sync"
    - git clone git@gitlab.com:i.a.bodrov85/tg_article_bot.git
    - cd tg_article_bot
    - git remote add github git@github.com/$GITHUB_USERNAME/tg_article_bot.git
    - git push github main
    - echo "Code synced to GitHub successfully"
  only:
    - main
  when: manual
