[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile.web-admin"

[deploy]
startCommand = "python web_admin_railway.py"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"

[deploy.envs]
NODE_ENV = "production"
