[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "python api_server.py"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[deploy.variables]
PORT = "5000"
ENVIRONMENT = "production"
LOG_LEVEL = "INFO"

# Эти переменные нужно будет установить в Railway Dashboard
# DATABASE_URL = "postgresql://..."
# REDIS_URL = "redis://..."
# ARTICLE_BOT_TOKEN = "..."
# OPENAI_API_KEY = "..."
