[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "python api_server_railway_full.py"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[deploy.variables]
PORT = "5000"
ENVIRONMENT = "production"
LOG_LEVEL = "INFO"

# Эти переменные нужно будет установить в Railway Dashboard
# DATABASE_URL = "postgresql://..."
# REDIS_URL = "redis://..."
# ARTICLE_BOT_TOKEN = "8016496837:AAHw5dv5b5X_Ad4GKBqVqzEH8izdS0aUytY"
# OPENAI_API_KEY = "..."
# JWT_SECRET_KEY = "..."
# API_KEY = "..."
