name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.railway_bot.txt
    
    - name: Test Railway integration imports
      run: |
        echo "🧪 Testing Railway integration imports..."
        python -c "from config_railway import RailwayConfig; print('✅ RailwayConfig imported')"
        python -c "from railway_api_client import RailwayAPIClient; print('✅ RailwayAPIClient imported')"
        python -c "from telegram_bot_railway import RailwayArticleBot; print('✅ RailwayArticleBot imported')"
        echo "✅ All Railway integration modules imported successfully!"
    
    - name: Test configuration
      run: |
        echo "🔧 Testing Railway configuration..."
        python test_bot_config.py
    
    - name: Test basic functionality
      run: |
        echo "🚀 Testing basic functionality..."
        python -c "import config; print('✅ Config loaded successfully')"
        python -c "import telegram_bot; print('✅ Telegram bot module imported')"
        python -c "import api_server; print('✅ API server module imported')"
        echo "✅ All basic modules working!"

  test-railway-api:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.railway_bot.txt
    
    - name: Test Railway API connection
      run: |
        echo "🌐 Testing Railway API connection..."
        python test_railway_integration.py
      env:
        RAILWAY_API_URL: https://tg-article-bot-api-production-12d6.up.railway.app
        USE_RAILWAY_API: true

  deploy:
    needs: [test, test-railway-api]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
    - uses: actions/checkout@v4
    
    - name: Deploy to Railway
      run: |
        echo "🚀 Deploying to Railway..."
        echo "Railway will automatically deploy from this repository"
        echo "Check Railway dashboard for deployment status"
    
    - name: Deploy to Render
      run: |
        echo "🚀 Deploying to Render..."
        echo "This would deploy the application to Render"
