name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run tests
      run: |
        echo "Hello from GitHub Actions!"
        echo "Testing basic functionality..."
        echo "GitHub Actions is working!"
    
    - name: Test imports
      run: |
        python -c "import config; print('Config loaded successfully')"
        python -c "import telegram_bot; print('Telegram bot module imported')"
        python -c "import api_server; print('API server module imported')"

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
    - uses: actions/checkout@v4
    
    - name: Deploy to Railway
      run: |
        echo "Deploying to Railway..."
        echo "This would deploy the application to Railway"
    
    - name: Deploy to Render
      run: |
        echo "Deploying to Render..."
        echo "This would deploy the application to Render"
